# Generated by Django 4.2.15 on 2024-08-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps_related', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ps_related.account')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('novice', 'Novice'), ('elite', 'Elite')], default='novice', max_length=10, verbose_name='Plan')),
                ('level', models.PositiveIntegerField(default=1)),
                ('link', models.URLField(blank=True, editable=False, null=True, unique=True, verbose_name='Link')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('is_paid', models.BooleanField(blank=True, default=True, verbose_name='Account Validity')),
                ('referrals', models.ManyToManyField(related_name='invites', to='ps_related.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='ps_related.plan'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
