# Generated by Django 4.2.15 on 2024-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_related', '0002_account_blog_plan_remove_student_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('in_stock', models.BooleanField()),
            ],
        ),
    ]
